### ISSUE TITLE
Selecting property types not available in the select list

### ISSUE THREAD

**Issue by Jonathan4083** [msawczyn/EFDesigner2022#40] opened 2022-07-11 15:07 UTC
We are using several db contexts. One of the contains enums we want to use in the other contexts. Because the Type-Property of entities is restricted to the select list we specified the type directly in the .efmodel file. Is there any reason not to remove the restriction of the type field in the designer?

**Comment by msawczyn** [comment] 2022-08-15 15:01
Duplicate of #28

**Closed by msawczyn** 2022-08-15 15:01 UTC
Labels: enhancement-M
